### ISSUE TITLE
Popraviti sljedeće pogreške (ispraviti kod tako da bude funkcionalan u odnosu na ostatak sustava)

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#10]
25) Popraviti sljedeće pogreške (ispraviti kod tako da bude funkcionalan u odnosu na ostatak sustava):
## Pogreška 1:

DATOTEKA: hash.c

POGREŠKA: SIGSEGV u funkciji AK_elem_hash_value() kada je pozvana iz
funkcije AK_create_hash_index()

OPIS: Na liniji 564 funkcija AK_create_hash_index() poziva funkcija
AK_elem_hash_value() i prosljeđuje joj referencu na temp_elem. Pozvana
funkcija pokušava iz prosljeđene reference dohvatiti vrijednost atributa
type (linija 31), ali to dovodi to poziva SIGSEGV.

UZROK: Na liniji 563 poziva se funkcija Ak_GetNth_L2() i rposljeđuju joj
se varijable l i row. Tokom debug-iranja saznalo se da je vrijednost
parametra l u tom trenutku jednak 0, što dovodi do toga da navedena
funkcija vraća NULL u varijablu temp_elem. To znači da aplikacija (unutar
funkcije AK_elem_hash_value()) pokušava dohvatiti nepostojeći podatak.
## Pogreška 2:

DATOTEKA: btree.c

POGREŠKA: SIGSEGV u funkciji AK_btree_insert()

OPIS: Na liniji 326 u funkciji AK_btree_insert() javlja se SIGSEGV.

UZROK (mogući): Vrijednost od root->root je možda prevelika (malo manje od
2.000.000.000) što dovodi do čitanje izvan dosega polja. Ta vrijednost se
poprimi nakon izvođenja funkcije memcpy() u liniji 322.

**Comment by LexyFOI** [comment]
Prijavljujem se za riješavanje ovog problema.

**Comment by djockovic** [comment]
Javljam se za rješavanje problema
