### ISSUE TITLE
SWIG Testovi

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#102]
Pregledati i provjeriti SWIG testove

**Comment by isolic811** [comment]
Testovi vezani uz update, delete i intersect uvijek padaju, selekcija radi samo na integerima

Problemi s funkcijama za dohvaćanje retka i preimenovanje tablice - test za preimenovanje tablice nije niti implementiran, a za dohvaćanje retka ne radi ispravno

Nepreglednost pokretanja testova - bolja solucija ih razdvojiti u više datoteka kako kod pokretanja testova ne bismo pregledavali milijun redaka

Testovi su nestabilni i prilikom pokretanja vise puta različit broj testova prođe, odnosno padne.
