### ISSUE TITLE
Popraviti AK_unique

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#105]
Popraviti AK_PRO na vrhu da se pokreće nakon incijalizacije varijabli.

Trenutna složenost provjeravanja ukoliko je constraint narušen u postojećim vrijednostima je n^2 što se može poboljšati na n.

Trenutno se AK_EPI nalazi u mrtvom djelu koda što se može jednostavno popraviti.

**Comment by TheWildHorse** [comment]
@mschatten Ovaj je riješen i testiran.
