### ISSUE TITLE
Popraviti trigger.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#106]
int AK_trigger_remove_by_name(char *name, char *table)

Funkcija dohvaća ID triggera s definiranim imenom i tablicom te ga obriše. Nakon toga potraži unos u AK_trigger_conditions tablici i ručno ga briše.

Prostor za poboljšanje:

    Koristiti AK_trigger_remove_by_obj_id za brisanje nakon dohvaćanja ID-a kako bi se izbjegla redudancija
    Dodati foreign key na AK_trigger_conditions tablicu kako bi se njen unos automatski obrisao

int AK_trigger_remove_by_obj_id(int obj_id)

Ista funkcionalnost kao i AK_trigger_remove_by_name, samo bez dohvaćanja IDa triggera.

Prostor za poboljšanje:

    Dodati foreign key na AK_trigger_conditions tablicu kako bi se njen unos automatski obrisao

int AK_trigger_edit(char name, char event, struct list_node condition, char table, char* function)

Funkcija prvo provjerava ukoliko su svi argumenti uneseni te ukoliko referencirani objekti postoje. Tada briše postojeći trigger i kreira novi s zadanim argumentima.

Prostor za poboljšanje:

    Razdvojiti funkciju Ak_Insert_New_Element_For_Update u logičke djelove da kod bude lakše čitljiv

struct list_node *AK_trigger_get_conditions(int trigger)

Vraća postfix listu uvjeta za trigger s navedenim ID.
int AK_trigger_rename(char *old_name, char *new_name, char *table)

Osvježuje red u AK_trigger tablici s novim imenom za postojeći trigger.

**Comment by TheWildHorse** [comment]
@mschatten Ja bi se javio da riješim prvi dio ovog taska i probam se poigrat s drugim. Mislim da bi treći trebao vrijedit jedno 300 bodova a ne 10 😛

**Comment by TheWildHorse** [comment]
@mschatten Prvi dio gotov, a za drugi treba prvo popraviti foreign key funkcionalnost da to mogu riješit. #34

**Comment by mschatten** [comment]
Issue zatvoren, nastavak u issue #138
