### ISSUE TITLE
int AK_read_constraint_unique(char* tableName, char attName[], char newValue[])

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#107]
Funkcija prvo izračunava količinu atributa u newValue. Ako je constraints tablica prazna, vraća EXIT_SUCCESS jer nema constraintova koji mogu biti nezadovoljeni. Tada prolazi kroz sve UNIQUE constraintove i traži constraint koji se odnosi na zadani tableName i attName. Ako takav ne postoji, vraća se EXIT_SUCCESS. Ako postoji i ta tablica nema zapisa, opet se vraća EXIT_SUCCESS. Ako ima zapisa onda pronalazi na kojem mjestu se nalazi koji atribut iz constrainta i provjerava sve redove ukoliko postoji neki kojem se svi atributi iz constrainta poklapaju s novim unosom te tada vraca EXIT_ERROR.

Prostor za poboljšanje:

    U kodu se stalno ponavlja isječak koda koji odvaja string s atributima odvojenim SEPARATORom. Taj isječak se može odvojiti u zasebnu helper funkciju i počistiti kod uvelike.
    Funkcija ima pun redundancije zbog lošeg rješavanja problema s provjeravanjem unosa u AK_constraints_unique tablici i ostalim tablicama. Ovo se može puno elegantnije riješiti i učiniti kod puno čitljivijim.

**Comment by darzunec1** [comment]
Preuzimam zadatak
