### ISSUE TITLE
int AK_create_theta_join_header(char *srcTable1, char * srcTable2, char *new_table)

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#109]
Funkcija prvo pročita imena atributa obje tablice te kreira novu tablicu s kombinacijom svih atributa. Ukoliko se neka dva atributa poklapaju imenom, na njih se dodaje prefix u obliku <ime_tablice.>.

Prostor za poboljšanje:

    Mikrooptimizacija - Refaktorirati algoritam za traženje duplikata u O(N) umjesto O(N^2)

**Comment by mateaB** [comment]
Javljam se za rješavanje ovog problema

**Comment by mschatten** [comment]
Raspodjeljeno u druge zadatke.
