### ISSUE TITLE
Popraviti opti: AK_rel_eq_assoc

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#110]
Svi testovi prolaze ali ne postoji programska provjera tocnosti(npr assert)

Glavne optimizacijske funkcije su prevelike 300-500 linija. Za svaki case u switchu implementaciju optimizaciju možemo izdvojiti u zasebnu funkciju.

AK_rel_eq_selection glavna funkcija sadrži copy/paste koda iz optimizacije AK_rel_eq_comut. Potrebno je refaktorirati na nacin da se koristi isti kod na oba mjesta(poziv funkcije iz odredenog librarya).

**Comment by Svarcf** [comment]
Javljam se za rješavanje ovog problema.
