### ISSUE TITLE
Napraviti dealokaciju u Ak_op_intersect i Ak_op_difference

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#112]
U cijeloj datoteci implementirati dealociranje memorije kod korištenja privremenih blokova

**Comment by nsinjori** [comment]
Javljam se za rješavanje ovog problema.

**Comment by mschatten** [comment]
Intersect i Difference

Uskladiti testove s:

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by pjadek** [comment]
Javljam se za rjesavanje ovog zadaka.
