### ISSUE TITLE
Popraviti AK_op_join test

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#113]
AK_op_join test ne prolazi! Ispisuje se poruka da tablica nat_join_test ne postoji.

**Comment by davbijeli** [comment]
Javljam se za rješavanje ovoga problema.

**Comment by mschatten** [comment]
Test 27 join daje (core dumped)

Test vraća 
*** Error in `./akdb': double free or corruption (out): 0x00005633ece7e600 ***
Aborted (core dumped)

Ispraviti pogrešku (potencijalno uz debuger)  te po potrebi složiti izvještavanje o testu u skladu s uputama na wiki stranici: 

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by mschatten** [comment]
Kod datoteke nat_join.c poprilično je dugačak i zbunjujući pa po tom pitanju moguće
su neke optimizacije
▪ Vidljivo je loše imenovanje varijabli

**Comment by corlukantonio** [comment]
Javljam se za rješavanje problema.

**Comment by kkupa** [comment]
Javljam se za rješavanje problema.

**Comment by kkupa** [comment]
Javljam se za rješavanje problema Testa opisanog u kodu
