### ISSUE TITLE
Popraviti Test 48: sql: Ak_constraint_between

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#114]
Uočeni nedostaci: Prvo pokretanje testa prolazi u redu, drugi pokušaj izbacuje nas iz programa uz poruku:

*********** Real SIGSEGV occured ***********
This means a memory address which is not under
our control has been accessed somewhere in your
code. Please use AK_calloc, AK_free, etc.
You've got some bugfixing to do disappointed
Probable current function: Ak_constraint_between_test
akdb: auxi/mempro.c:134: AK_debmod_signal_callback: Assertion `mprotect_sigsegv' failed.
Aborted (core dumped)

Također, kod je prilično opsežan i može ga se bolje strukturirati radi lakše preglednosti.

**Comment by nkuzir** [comment]
Javljam se za rješavanje uočenih problema.

**Comment by lkoscak** [comment]
javljam se za rješavanje problema.

**Comment by mschatten** [comment]
U ovom trenutku javlja se drugačija greška u drugom prolazu na prvom testu, odnosno javlja se "*** stack smashing detected ***: terminated"

Osim navedenog problema može se primijetiti da se testiranja odnose samo na tekstualne vrijednosti zbog čega bi trebalo omogućiti rad i s brojčanim vrijednostima, u budućnosti i s temporalnim

**Comment by brajic** [comment]
Javljam se za rješavanje ovog problema.
