### ISSUE TITLE
Popraviti Test 49: sql: AK_check_constraint i Test 50: sql: AK_constraint_name  

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#115]
Test 49
Prvo pokretanje testa prolazi u redu, drugo pokretanje ne prolazi kako je očekivano, testiranja nisu dobra i ne prolaze svi testovi koji bi trebali - od šest testova, tri su prošla očekivano (success ili failure),
dok su 3 imala obrnuti ishod. 1. Test prolazi, 2. Test pada, 3. Test pada, 4. Test prolazi, 5. Test pada 6. Test prolazi.

Test 50
Test svaki puta uredno prolazi, no potrebno je provjeriti jesu li sva ograničenja obuhvaćena provjerom i eventualno dodati ukoliko neko fali.

**Comment by darmirkov** [comment]
Javljam se za rješavanje zadatka.

**Comment by mschatten** [comment]
Popraviti samo test 50 (2 testa ne rade)
