### ISSUE TITLE
Popraviti NOT NULL i VIEW

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#117]
NOT NULL

Trenutno ne vidim razlog zašto bi AK_read_constraint_not_null funkcija bila zasebna funkcija zato jer služi samo za ispis i provjeru tj. testiranje podataka u tesnoj funkciji.

Isto tako bi trebalo razdvojiti jednu veliku funkciju koja provjerava sve i postavlja ograničenje u dvije od kojih jedna provjerava a druga postavlja

VIEW

Postoje dvije funkcije koje imaju skoro isti kod. Jedna uklanja pogled po view ID, a druga po nazivu. To bi se moglo staviti u jednu funkciju gdje se provjerava koji je parametar unjet i prema tome se određuje te briše pogled.

**Comment by nkuzir** [comment]
Javljam se za rjesavanje zadatka.
