### ISSUE TITLE
Popraviti SELECT

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#118]
SELECT

Jedna tablica se zove “select_table”. Tamo se stavljaju svi atributi tablice student, a onda se u “help_table” stavljaju atributi koji su navedeni u SELECT upitu.

Problem je da upit u sebi ima uvjet da godina mora biti veća od 2005, a vraćaju se svi studenti, čak I oni kojima je godina manja od 2005. Na kraju testa ispod ispisa cache memorije ruši se program:

Error in './akdb': double free or corruption (!prev): Aborted (core dumped)

Mogući razlog ove greške je taj da se dvaput oslobađa temp_block u glavnoj funkciji. Nakon prvog oslobađanja se još uvijek koristi taj temp i onda program ne zna što s tim, tako da se zapravo treba osloboditi temp.

Također bi trebalo malo format koda (ident) popraviti jer nije baš pregledno, no to nema utjecaja na funkcionalnost.

**Comment by mschatten** [comment]
Iz starog issue-a:

    select.c

    Test vraća pogrešne rezultate (osnovni uvjet zadan u WHERE dijelu upita nije zadovoljen)
    Test na kraju vraća error i poruku „core dumped“

**Comment by ZMehanovic** [comment]
javljam se za rješavanje

**Comment by mschatten** [comment]
Test 41 SELECT daje SIGSEGV

Provjeriti (uz debugger) o čemu je riječ i ispraviti pogreške. Nakon otklanjanja SIGSEGV errora analizirati logičku ispravnost implementacije te po potrebi složiti izvještavanje o testu u skladu s uputama na wiki stranici: 

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by kpavleka** [comment]
Javljam se za rješavanje problema
