### ISSUE TITLE
Popraviti AK_sequence

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#119]
Modul u kojem se nalazi: file ->sequence.c

    AK_sequence_add – funkcija za dodavanje sekvence

    AK_sequence_remove – funkcija za uklanjanje sekvence

    AK_sequence_current_value – funkcija vraća trenutnu vrijednost sekvence

    AK_sequnece_next_value – funkcija vraća vrijednost sljedeće sekvence i zapisuje je u sistemsku tablicu kao trenutnu vrijednost

    AK_sequence_get_id – funkcija koja dohvaća trenutni id sekvence

    AK_sequence_rename – funkcija koja preimenuje sekvencu

    AK_sequence_modify – funkcija koja služi za modifikaciju sekvence

    AK_sequence_test – funkcija za testiranje sekvence

Test nije uspješan, raspadne se kod modificiranja sekvence.

**Comment by TheWildHorse** [comment]
@mschatten Javljam se za rješavanje ovog zadatka.

**Comment by TheWildHorse** [comment]
@mschatten Testirao i test radi sasvim ok...
