### ISSUE TITLE
Popraviti Test 11 file: AK_op_rename

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#120]
Test preimenovanja operatora.

    MODUL: file
    GREŠKE: DA
    POBOLJŠANJE: fix bug-a

************* Real SIGSEGV occured *************
This means a memory address which is not under
our control has been accessed somewhere in your
code. Please use AK_calloc, AK_free, etc.
You've got some bugfixing to do :(
Probable current function: AK_delete_segment
akdb: auxi/mempro.c:134: AK_debmod_signal_callback: Assertion `mprotect_sigsegv' failed.
Aborted (core dumped)

**Comment by matijah9** [comment]
Javljam se za rješavanje ovog issue-a.
