### ISSUE TITLE
Popraviti Test 10 file: Ak_fileio_test

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#121]
Kod pokretanja testa kreira se tablica "testna". Podaci se dodaju preko ove linije koda: int AK_add_to_redolog (int command, struct list_node ∗ row_root). Dodano je devet zapisa u tablici. Nakon toga se prema dva zajednička atributa zapisi u tablici ažuriraju.

    MODUL: file
    GREŠKE: nema
    POBOLJŠANJE: - strukturiranje koda (nejasno i nepregledno definirane varijable, drugim načinom pisanja kod se može smanjiti)

Ak_Insert_New_Element_For_Update - funkcija za unos novog elementa nakon nekog elementa
Ak_insert_row_to_block - funkcija za unos novog elementa u blok
Ak_insert_row - funkcija unosi jedan red u tablicu
Ak_update_row_from_block - ažuriranje podataka u elementu bloka
Ak_delete_row_from_block - brisanje redka iz bloka
Ak_delete_update_segment - funkcija ažurira ili briše cijeli segment tablice
Ak_delete_row - brisanje redka
Ak_delete_row_by_id - brisanje redka prema ID-u
Ak_update_row - ažuriranje redka
Ak_fileio_test - funkcija za pokretanje testa

modifikacija funkcija koja se proteže kroz cijeli kod -> Ak_Insert_New_Element_For_Update

**Comment by pjadek** [comment]
Javljam se za rjesenje ovog zadatka
