### ISSUE TITLE
Razdvojiti funkciju Ak_Insert_New_Element_For_Update 

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#138]
Razdvojiti funkciju Ak_Insert_New_Element_For_Update u logičke djelove da kod bude lakše čitljiv. Funkcija je razdvojena u datoteci fileio.c (issue #106), sada bi ju trebalo pronaći kroz čitavi kod i prema potrebi zamijeniti s Ak_Update_Existing_Element odnosno  Ak_Insert_New_Element kako bi bilo jasno o kojoj se operaciji radi.

**Comment by darmirkov** [comment]
Javljam se za rješavanje ovog problema.
