### ISSUE TITLE
Popraviti operator selekcije

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#14]
21) Popraviti operator selekcije: operator selekcije ne radi kako spada. Konstantno upisuje zapise iz src tablice na kraj dest tablice. Te iz tog razloga sve operacije koje koriste operator selekcije ne rade kako spada imamo puno redundantnih zapisa. Provjeriti testove (posebice destinacijske tablice) i osigurati da se rezultat uvijek zapisuje u novu destinacijsku tablicu.

**Comment by fstrunja** [comment]
Ja bih ovo.
