### ISSUE TITLE
Test 37 - Command daje SIGSEGV

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#159]
Napisani test ne prolazi iz razloga što se pojavi SIGSEGV error kod izvršavanja SELECT naredbe
U testnom primjeru za INSERT naredbu id studenta koji se unosi je 35917, međutim nakon izvršavanja naredbe u tablicu se kao id studenta zapiše null dok se ostali atributi ispravno zapišu u tablicu
Kod testiranja UPDATE naredbe retku s studentID=35900 se ime mijenja u FOI, međutim nakon izvršavanja naredbe I ispisa tablice nije vidljiva promjena u tome retku
SELECT naredba ruši aplikaciju zbog SIGSEGV errora

Ispravak INSERT naredbe da se ispravno zapiše id
Ispravak UPDATE naredbe da se ispravno ažurira željeni atribut
Rješavanje SIGSEGV errora kod SELECT naredbe
Nakon rješavanja SIGSEGV errora po potrebi ispraviti ostatak implementacije te po potrebi složiti izvještavanje o testu u skladu s uputama na wiki stranici: 

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by fkraljic** [comment]
Javljam se za rješavanje ovog problema

**Comment by marezina** [comment]
Javljam se za rješavanje ovog problema.
