### ISSUE TITLE
archive_log

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#160]
Doraditi dinamičko imenovanje binarnih datoteka prilikom spremanja uz pomoć timestamp-a.

Detaljniji komentari za neke linije koda
Izbacivanje linija koda koje se više ne koriste (primjerice metoda void AK_empty_archive_log())
Osigurati da stvaranje novog direktorija funkcionira i na MAC platformi (funkcija int AK_check_folder_archivelog() → linija return mkdir(ARCHIVELOG_PATH, 0755); // not sure if this works on mac)
Također, u funkciji int AK_check_folder_archivelog(), u slučaju da postoji nešto, ali to nije folder, trebalo bi korisniku dati neku opciju pomoću koje bi stvorio novi folder na neki način, umjesto da taj dio grananja stoji prazan → dio koda:
      else {
          /* exists but is no folder */
         }

**Comment by matijah9** [comment]
Javljam se za rješavanje ovog problema.
