### ISSUE TITLE
recovery.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#161]
Omogućiti učitavanje zadnje log datoteke ili izbor između više log datoteka.

Detaljnije komentirati kod.

Ukloniti nepotrebne linije koda.

Nakon neuspješnog otvaranja datoteke napraviti još neku opciju kojom bi se pokušalo uspješno otvoriti datoteku ukoliko ona postoji → funkcija void AK_recover_archive_log(char* fileName)

**Comment by evituri** [comment]
Javljam se za rješavanje.

**Comment by mvecenaj** [comment]
Ako je _issue_ dostupan, javljam se za rješavanje.

**Comment by mvecenaj** [comment]
Poštovani profesore,
pod učitavanjem log datoteke podrazumijevate ispis sadržaja ili izvršavanje recovery operacije navedene log datoteke?

**Comment by mschatten** [comment]
Naravno na recovery operaciju, ovo bi bilo pomalo trivijalan zadatak ;-)

**Comment by mvecenaj** [comment]
Jasno onda! : D
