### ISSUE TITLE
Test 43 unique

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#162]
Detaljno utvrditi uzrok neprolaska testa te navedeno popraviti (Pokretanje testa rezultira s više različitih failure-a te ponekad s memory leak-om.). Također, popraviti način izvještavanje o testu u skladu s uputama na wiki stranici: 

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by AntonijaPofuk** [comment]
Javljam se za rješavanje ovog problema.

**Comment by brajic** [comment]
Javljam se za rješavanje ovog problema.

**Comment by mschatten** [comment]
Nekoliko dodatnih informacija:

Prvim pokretanjem testova 2 testa ne uspijevaju
Jedan se odnosi na postavljanje UNIQUE ograničenja na atribut firstName koji već sadrži vrijednosti koje se ponavljaju (na drugoj slici možemo vidjeti dva retka s imenom „Ivan”)
Problem je što se ovdje očekuje EXIT_SUCCESS, a ne EXIT_ERROR što je očekivano s obzirom na to da funkcija ispravno uočava da postoji UNIQUE violation

Slični problem je i kod testa 7
Ovdje vidimo da se pokušava postaviti UNIQUE ograničenje nad atributom koji već ima ograničenje što funkcija uočava i ispisuje grešku zbog čega bi se opet trebao očekivati EXIT_ERROR za prolaz testa

Još jedan problem kod drugog prolaska testiranja jest što iz nekog razloga ne prolazi brisanje već postojećeg ograničenja što nije slučaj kod prvog prolaska
Test 2 odnosi se na brisanje ograničenja yearUnique, a u tablici na prvoj slici vidimo da ograničenje i dalje postoji i nakon brisanja
