### ISSUE TITLE
Unaprijeđenje dokumentacije i wiki

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#163]
- dokumentacija - instalacija i pokretanje -> napraviti više user friendly
- dokumentacija popis funkcionalnosti više user friendly
- dokumentacija općenito poboljšati dizajn i ažurirati, po potrebi napraviti odgovarajuće wiki stranice

Čišćenje dokumentacije u kodu:

U mnogim datotekama komentari koji se uvoze u Doxygen, ali i općenito opisuju kod su neispravni ili zastarjeli, npr.:

Theta_join.h sadrži komentare koda za implementaciju, a već su implementirani
Potrebno je ispraviti dobar dio dokumentacije (komentara) unutar /rel/ direktorija (e.g. engleska gramatika).
Komentari u .h datotekama govore da one sadrže strukture, no u većini slučaja sadrže samo metode bez ikakvih struktura.

itd.

Potrebno je sustavno proći kroz sve komentare i ispraviti ih gdje je to moguće, nadopuniti ako neki dio koda nije
dokumentiran odnosno obrisati nepotrebne i zastarjele komentare.

**Comment by ivanmilas1** [comment]
Javljam se za rješavanje.

**Comment by JodaVz** [comment]
javljam se za riješenje problema, posebice onih opisanih u mojoj prvoj zadaći

**Comment by goranalkovic** [comment]
Javljam se za rješavanje
