### ISSUE TITLE
Testovi 31 i 32 (selection) daju (core dumped)

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#168]
Test vraća
Assertion `mprotect_sigsegv' failed.
Aborted (core dumped)

Ispraviti pogreške (potencijalno uz debuger)  te po potrebi složiti izvještavanje o testu u skladu s uputama na wiki stranici: 

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by fkraljic** [comment]
Javljam se za rješavanje ovog problema

**Comment by fbelinic** [comment]
Poštovani, javljam se za rješavanje ovog problema!
