### ISSUE TITLE
Produkt

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#169]
Potrebno je provjeriti zašto test kaže da je tablica prazna i potrebno je rezultat, ako postoji, ispisati. 

Postoji drugi test koji se ne nalazi u izborniku sučelja za pokretanje testova, potrebno je oba testa spojiti u jedan.

Obavezno implementirati testove u skladu s:

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by fkraljic** [comment]
Javljam se za rješavanje problema

**Comment by mschatten** [comment]
Kod datoteke product.c moguće je upotpuniti s više komentara s objašnjenjima testne
funkcije

Kod pojedinih funkcija u datoteci nedostaje komentar koji objašnjava povratnu
vrijednost tih funkcija – moguće poboljšanje u smislu dokumentiranja

**Comment by ghost** [comment]
Javljam se za rješavanje ovog zadatka. (Ivan Fran Hodak, ihodak).

**Comment by kkupa** [comment]
Javljam se za rješavanje problema.
