### ISSUE TITLE
Test 15 table vraća SIGSEGV

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#172]
Provjeriti (uz debugger) o čemu je riječ i ispraviti pogreške. Nakon otklanjanja SIGSEGV errora analizirati logičku ispravnost implementacije te po potrebi složiti izvještavanje o testu u skladu s uputama na wiki stranici: 

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by kpavleka** [comment]
Javljam se za rješenje ovog problema

**Comment by lkoscak** [comment]
Javljam se za rješavanje problema.
