### ISSUE TITLE
Refaktorizacija Python servera

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#174]
Potrebno je napraviti refaktorizaciju koda kako bi se smanjila redundancija, integrirali dijelovi koji suštinski idu zajedno, odnosno razdvojili dijelovi koji ne idu. Implementirati automatske testove komponenti servera.

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by JodaVz** [comment]
javljam se za riješenje problema
