### ISSUE TITLE
Poboljšanje komunikacije između servera i klijenta

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#177]
Umjesto slanja/primanja stringova, bolje bi bilo zapakirati podatke u JSON format (vidi #16).

Implementirati slanje/primanje međurezultata. Npr. pri izvršavanju SELECT upita poslati svaki
redak posebno onim tempom kako se naredba izvršava. U slučaju upita kojemu treba puno vremena,
korisnik će vidjeti neke rezultate odmah umjesto da čeka da se izvrši cijeli upit.

Ostvariti zatvaranje socketa pri prisilnom gašenju servera i omogućiti gašenje unutar programa.

**Comment by JodaVz** [comment]
javljam se za riješenje problema

**Comment by rmaruseve** [comment]
Javljam se za rješenje ovog problema
