### ISSUE TITLE
Popisati i popraviti memory leakove

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#18]
8)  popisati i popraviti memory leakove (koristiti mempro i neki debugger, npr gdb ili valgrind)

**Comment by elvispopovic** [comment]
Ako ovaj issue nije riješen, mogao bih to pogledati.

**Comment by elvispopovic** [comment]
Preuzimam ovaj zadatak/issue.

**Comment by elvispopovic** [comment]
Current brief list of detected memory leaks (using Valgrind):
by 0x456686: AK_get_tuple (table.c:356)
by 0x43BF90: AK_init_block (dbman.c:615)
 by 0x456686: AK_get_tuple (table.c:356)
 by 0x4562C4: AK_get_row (table.c:297)
 by 0x455DB7: AK_get_header (table.c:188)
 by 0x446E00: Ak_Insert_New_Element_For_Update (fileio.c:39)
 by 0x446944: AK_initialize_new_segment (files.c:52)
 by 0x445578: AK_get_segment_addresses_internal (memoman.c:526)
 by 0x43E813: AK_create_header (dbman.c:1565)
 by 0x40AFBB: dictionary_new (dictionary.c:132)
 by 0x4059FC: AK_create_test_tables (test.c:311)
 by 0x45698D: AK_tuple_to_string (table.c:402)
 by 0x445578: AK_get_segment_addresses_internal (memoman.c:526)
 
 by 0x414A3C: AK_check_attributes (redo_log.c:151)
 by 0x414420: AK_add_to_redolog (redo_log.c:51) -- fixed
 by 0x444D6F: AK_query_mem_AK_malloc (memoman.c:234)
