### ISSUE TITLE
Prikaz sistemskog kataloga u klijentu

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#180]
Implementirati odgovarajuće metanaredbe (slično kao u psql-u) za prikaz svih tablica iz sistemskog kataloga. Pri tome koristiti SQL, ne izravno c-funkcije.

**Comment by jkristovi** [comment]
Javljam se za rješavanje ovog problema.

**Comment by IvanJ5** [comment]
Javljam se za rješavanje ovog problema.
