### ISSUE TITLE
Implementacija Ak_user_check_user(usr,pass)

### ISSUE THREAD

**Issue by JodaVz** [AILab-FOI/akdb#215]
Trenutna implementacija prijave radi na principu provjere da li postoji ID vezan uz korisničko ime, odnosno da li postoji zapis korisnika. Ne provjerava se lozinka i korisničko ime u paru, kao što bi trebalo, jer ne postoji metoda za dohvaćanje i provjeru istih.

**Comment by mschatten** [comment]
server_functions.py
Promijeniti metodu check_auth_password(username, password) tako
da uistinu provjerava postoji li upisano korisničko ime i lozinka u bazi
(trenutačno je prijava moguća jedino s korisničkim imenom testingUser
i lozinkom testingPass

**Comment by fmikolic** [comment]
Javljam se za ovaj zadatak.
