### ISSUE TITLE
Ispravci view i select

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#216]
View
------

Kod je čitljiv no postoje gramatičke greške u komentarima i postoje komentari koji ničemu ne služe (komentiran dio koda koji se više ne koristi)

Kod bi se mogao poboljšati nekim provjerama ispravnosti ulaznih parametra (npr. Provjera postojanja pogleda (view) u tablici i slično)

AK_view_add
Moguće poboljšanje: Dodati dio koda koji provjera da li već postoji upit s istim imenom te vratiti EXIT_ERROR ako postoji

AK_view_rename
Ovdje se dvaput poziva ista linija koda „result = AK_view_remove_by_name(name);” pa bi se to dalo promijeniti. Također nema provjere da li to ime uopće postoji u tablici

Select
--------
Programski kod je čitljiv, ali postoje suvišni komentari koji su ostali od starog koda. 
Također select.h dvaput uključuje datoteku „/file/table.h”

**Comment by skisic** [comment]
Javljam se za rješavanje issue-a
