### ISSUE TITLE
Ispravci server i klijent

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#219]
Komentari u nekim skirptama su na pogrešnom mjestu popraviti
◦ npr. ispred krive funkcije 181., 182. linija skripta sql_executor.py
Na raznim mjestima u kodu nalaze se oznake #todo, s pretpostavkom da to nije implementirano, provjeriti što radi onaj dio koda koji je napisan
(i koristi li se) i implementirati do kraja.
◦ npr. akdb_cli.py - funcije def recv_data(self): i def send_command(self, cmd), sadrže komentare #TODO implement protocol, linije (371 i 379)
Prilikom prvog pokretanja datoteke python server.py dolazi do greške ImportError: No module named paramiko, i ImportError: No module
named configparser. (nakon instaliranja paramiko) Moguće dodati instalaciju modula u kod ili setup.
Naredba testme pada na CREATETABLE, ustanoviti zašto (povezano za naredbu execute i broj argumenata), popraviti i provjeriti ispravnost
ostalih implementiranih testova pri pozivu ove naredbe .

**Comment by mschatten** [comment]
Obratiti pozornost na #176

**Comment by mschatten** [comment]
Potrebno je refaktorizirati kod klijenta odnosno akdb_cli.py na više datoteka, tako da se lakše otkriju moguće greške i da kod bude pregledniji. Isto napraviti kod sql_executor datoteke

Isprogramirati neke od osnovnih SQL naredbi koje nedostaju, za lakše komuniciranje servera i klijenta. Primjer: TRUNCATE – za brisanje podataka iz tablice; ALTER DATABASE – mijenjanje trenutne baze u kojoj radimo; i slično (nakon što se popravi swig sučelje - vidi: #173)

Popratiti naredbe koje postoje u C programskom jeziku sa onima u Pythonu, tako da su u potpunosti funkcionalne. Primjer: int AK_trigger_edit() , int AK_trigger_rename() za ostvarivanje ALTER triggera

**Comment by mbenkus** [comment]
Javljam se za rješavanje zadatka.
