### ISSUE TITLE
Implementirati CHECK constraint

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#22]
Provjeriti je li postoji neki dio u SELECT naredbi (WHERE klauzula) koji je iskoristiv. Bilo bi dobro da je sustav za provjeravanje formule obzirom na red u tablici jedinstven na razini sustava.

**Comment by mschatten** [comment]
Check ograničenje na razini tablice

Implementirati funkcionalnost stvaranja check ograničenja na razini cijele tablice (ne samo na razini jednog stupca). Obavezno implementirati testove u skladu s:

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by mschatten** [comment]
check_constraint: Testovi nisu najefikasnije napisani, ne rade kako je predviđeno

**Comment by bpilosta** [comment]
Javljam se za rješavanje

**Comment by mschatten** [comment]
Ne rade neki testovi, potrebno ih je provjeriti i popraviti.

**Comment by mschatten** [comment]
Dodatne informacije:

Kod prvog testiranja neki testovi prolaze, a neki ne, dok u drugom testiranju nijedan test ne prolazi
Također, vrlo teško je uočiti što se točno događa prilikom testiranja pošto nije implementirano ispisivanje tablice CHECK ograničenja kao ni osnovan opis testa


Može se primijetiti da je kod nekih testova u komentaru napisano da bi test trebao failati
Kako bi TEST 1 bio uspješan trebalo je predvidjeti EXIT_ERROR, a ne EXIT_SUCCESS pošto je sustav uočio „constraint violation”
Smatram da je u testove bilo potrebno unijeti ispis tablice CHECK ograničenja kako bi se lakše i efikasnije uočila greška kao što je to slučaj kod implementacije ostalih ograničenja

Osim spomenutog čini se da nije implementirano brisanje CHECK ograničenja pošto ponovnim prolazom nijedan test ne uspijeva
To možemo vidjeti primjerice u drugom prolazu kod testova 2 i 3
U testu 1 u jednoj liniji koda se spominje AK_drop("DROP_CONSTRAINT","check_student_year");
Navedeno bi trebalo brisati ograničenje, no pregledom implementacije AK_drop funkcije vidimo da su na ovaj način implementirani samo brisanja UNIQUE, NOT NULL i BETWEEN ograničenja
