### ISSUE TITLE
Popraviti projection.c|h

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#223]
Kod datoteke projection.c moguće je mnogo poboljšati u vidu ispravljanja nelogičnosti u imenovanju kako
funkcija, tako i parametara i varijabli

U datoteci u mnogome nedostaju popratni komentari, a moguće je i poboljšanje u smislu dokumentiranja, budući da za pojedine funkcije nisu pravilno i cjelovito popisani parametri ni povratne vrijednosti

Postoje funkcije koje nisu pravilno imenovane poput AK_perform_operatrion koja sadrži pogrešku prilikom pisanja riječi operation, removeSubstring nije imenovana u skladu s imenovanjem svih funkcija ove aplikacije

Datoteka sadrži funkcije čija je namjena nejasna ili loše definirana (AK_get_operator, removeSubstring)

Krajnji zaključak je da je datoteka općenito loše strukturirana i komplicirana za analiziranje – moguće poboljšanje

Pri popravcima obavezno povesti računa o tome da ako se preimenovani nazivi koriste u drugim datotekama (.c, .h. .i, .py itd.) da se preimenuju i u povezanim datotekama.

**Comment by irenailisevic** [comment]
Javljam se za rješavanje zadatka.
