### ISSUE TITLE
Implementirati primary key i foreign key/references ograničenja

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#224]
Potrebno je koristiti postojeća ograničenja (unique, not null) i postojeće SQL naredbe i strukture (npr. index, select) za implementaciju ograničenja primarnog ključa (potencijalno nad više atributa) i ograničenja referencijalnog integriteta (foreign key/references). Pri potonjem obratiti pozornost na strategije upravljanja referencijalnim integritetom (on delete/update cascade/restrict/set default/null).

**Comment by mkrznaric** [comment]
Javljam se za rješavanje zadatka.

**Comment by zpetricus1** [comment]
Javljam se za rješavanje zadatka
