### ISSUE TITLE
Popraviti datoteke zaglavlja

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#228]
Gotovo svaka datoteka zaglavlja ( .h ) pri kraju ima nekolicinu funkcija koje nemaju komentare nego su nabacane redom, te funkcije su kasnije objašnjene u djelu njihove implementacije ( u .c datoteci ), no za brzi uvid u sadržaj .c biblioteke bilo bi dobro te funkcije komentirati i objasniti i u pripadajućem .h zaglavlju.

Pregedati sve datoteke zaglavlja (.h) i popraviti komentare gdje je potrebno.

**Comment by vbencek** [comment]
javljam se za rjesavanje ovog zadataka
