### ISSUE TITLE
Popraviti dokumentaciju i doxygen

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#245]
Doxygen:
Generirane HTML datoteke nisu sve u potpunosti funkcionalne
Početna stranica dokumentacije (index.html) prikazuje samo naslov aplikacije bez opcije pregleda daljnje dokumentacije
Nedostaje navigacija dokumentacije (nemogućnost povratka na početnu stranicu ili drugi document dokumentacije) i formatiranje je nedorađeno
Nedostaje podrška za UTF-8.

html_files/*
Datoteke za modificiranje generiranih datoteka dokumentacije
Uključuju datoteke za dodavanje zaglavlja i podnožja, formatiranja i JavaScript koda kod pokretanja
Putanje do ovih datoteka se postavljaju u doxygen.config datoteci
U projektu je njihov je sadržaj prazan i zbog toga su formatiranje i navigacija nepostojeći

Dokumentacija:
Nepotpune upute za podešavanje projekta na macOS-u
Nije dovoljno kopirati Linux korake

**Comment by tbencic** [comment]
Profesore, javljam se za ovaj issue

**Comment by mschatten** [comment]
Dodatne informacije:
Trenutno extract_all je postavljen na no, što znači kako doxygen neće izvući elemente koji nisu dokumentirani
Elementi unutar html_files foldera nisu bili funkcionalni te ih je potrebno ručno napraviti za ispravan rad
