### ISSUE TITLE
Mempro - implementacija testa

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#246]
AK_mempro_test je implementirana ali ne postoji na glavnom meniju za testove. Dodati na meni. Povesti računa o tome da testovi budu u skladu s https://github.com/AILab-FOI/akdb/wiki/Reporting-Test-Results
Nakon toga testirati i provjeriti radi li test. Ako ne radi, popraviti.

**Comment by sdujakovi** [comment]
Javljam se za rješavanje zadatka.
