### ISSUE TITLE
Aggregation - TODO ispravci

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#249]
Postoje neke struct definicije koje su opisane unutar klase, a nisu u
headeru (246: struct list_node)

Dijelovi koda nisu dovršeni kako je zamišljeno (656: TODO replace this
segment with AK_drop_table() once when it's done)

435: FILE - fix this!
634: move struct to .h
674: Needs description

**Comment by ghost** [comment]
Javljam se za rješavanje

**Comment by edujak** [comment]
Javljam se za rješavanje. (Edit: issue je originalno s moje prezentacije)

**Comment by mschatten** [comment]
Kolegica @edujak  ima prednost jer je ona uočila problem. Molim kolegicu @mararki da odabere drugi zadatak.

**Comment by mschatten** [comment]
Testiranjem je utvrđeno da ispravci onemogućuju kompajliranje (make), tj. javlja se pogreška:

gcc -pthread -w -c -g -c -w rel/aggregation.c -o rel/aggregation.o
In file included from rel/aggregation.c:20:
rel/aggregation.h:60:31: error: initializer element is not constant
   60 | struct list_node * row_root = (struct list_node*) AK_malloc(sizeof(struct list_node));
      |                               ^
rel/aggregation.h:62:37: error: initializer element is not constant
   62 | struct list_node * projection_att = (struct list_node*) AK_malloc(sizeof(struct list_node));
      |                                     ^
make: *** [Makefile:20: rel/aggregation.o] Error 1

Molim ispraviti.
