### ISSUE TITLE
Test 3 - view

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#253]
U svakom sljedećem testiranju nakon prvog test 3 nije prošao
*** TEST 3 – RENAME VIEW ****
Renaming ‘view3’ to ‘view300’…
Test 3 faild!
Test 3 ne prolazi zbog toga što već prije toga postoji pogled pod imenom view300
Taj problem zapravo i nije problem jer poštiva ograničenje nad tablicom koja je UNIQUE, ali taj problem se može riješiti da svakim novim pokretanjem testa preimenovanje npr. ‘view3’ se preimenuje u ‘view’+ broj pokretanja testa ‘view301’, ‘view302’,…

**Comment by jdumencic** [comment]
Profesore javljam se za ovaj issue.

**Comment by TKolar10** [comment]
Javljam se za rješavanje.

**Comment by mschatten** [comment]
Kolega @TKolar10 ima prednost jer je on pronašao pogrešku u svojoj prezentaciji.
