### ISSUE TITLE
Unaprijediti projection.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#255]
AK_get_operator mogao bi se elegantnije riješiti kroz switch case.
if(strstr(exp,"+"))
 return "+";
else if(strstr(exp,"-"))
 return "-";
else if(strstr(exp,"/"))
 return "/";
else if(strstr(exp,"%"))
 return "%";
else if(strstr(exp,"*"))
 return "*";
- AK_copy_block_projection bi mogao biti bolje objašnjen uz dodatne komentare na pojedinačnim blokovima ključnim za funkciju.

**Comment by sdujakovi** [comment]
Javljam se za rješavanje.
