### ISSUE TITLE
View - dodatni testovi i imenovanje varijabli

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#256]
Eventualno bi se mogli dodati testovi za ostale sadržane funkcije. Potrebno provjeriti koje se funkcije ne testiraju i implementirati odgovarajuće testove.

Nazivi funkcija i varijabla su većinom smisleni iako bi možda bilo bolje da se koriste puni izrazi u nazivu pojedinih funkcija kao što je AK_get_rel_exp. Potrebno je preimenovati funkcije tako da se koriste puni nazivi uz pažnju da se preimenuje i u ostalim dijalovima sustava gdje se te funkcije koriste. Također, posebice obratiti pažnju na make swig (možda će biti potrebno editirati interface datoteku, ako ne prođe make swig).

**Comment by jvresk** [comment]
Javljam se za ovaj issue.
