### ISSUE TITLE
Popraviti web stranicu (docs)

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#258]
Popraviti:
* Source Forge link više ne postoji
* Nekonzistentni gumbi, negdje se može kliknuti na sam gumb, a negdje ne:
* Ikone nisu centrirane
* Neintuitivno pregledavanje slika

Provjeriti je li dokumentacija up-to-date i je li možda nedostaju neke ključne informacije. Ako je tomu tako, popraviti i/ili nadodati.

**Comment by nbekavac** [comment]
Javljam se za rješavanje ovog problema.
