### ISSUE TITLE
Popraviti funkciju brisanja ograničenja

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#265]
Trenutno je moguće unijeti nova ograničenja u tablicu ograničenja i obrisati ograničenje jedanput. Nakon ponovnog zvanja funkcije za brisanje bilo kojeg ograničenja koje se nalazi u talibici ograničenja, u oba slučaja (UNIQUE, NNULL), funkcija brisanja vraća EXIT_SUCCESS, no ograničenje se ne briše. Funkcija brisanja UNIQUE ograničenja (AK_delete_constraint_unique) definirana je u datoteci "unique.c", dok je funkcija za brisanje NNULL ograničenja (AK_delete_constraint_not_null) definirana u datoteci "nnull.c".

**Comment by bpilosta** [comment]
Javljam se za rješavanje ovog problema.
