### ISSUE TITLE
Popraviti dodjelu prava korisniku i grupi kod privileges.c 

### ISSUE THREAD

**Issue by bzitkovic** [AILab-FOI/akdb#266]
Kod dodjele prava korisniku i grupi podaci se upisuju u nepostojeće stupce, te se iz tog razloga u tablice upisuje vrijednost NULL. Tako da kod provjere dodjeljenjih prava ne može se na ispravan način provjeriti koja prava određeni korisnik ili grupa ima. Isto tako, nakon toga popraviti da prolazi test 14 koji je vezan za taj problem.

**Comment by brajic** [comment]
Javljam se za rješavanje ovog problema.

**Comment by bzitkovic** [comment]
> Javljam se za rješavanje ovog problema.

Kolega, to je moj issue :)

**Comment by brajic** [comment]
Oops kolega ispričavam se :sweat_smile:
