### ISSUE TITLE
6) Btree.c - test

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#47]
6) Btree.c
Test pada, greske je vec spomenuo kolega Danijel Filipovic(?)
Funkcija void AK_btree_search_delete bi mogla biti razdvojena u 2
funkcije(1 za trazenje elementa a 1 za brisanje)
--> ispraviti i razdvojiti

**Comment by mschatten** [comment]
TEST 17 - BTREE
testiranje pada prilikom umetanja u stablo te pretraživanja/brisanja
nije uspješno dohvaćena adresa bloka,
mogući problemi kod
int adr_to_read = (int) AK_find_AK_free_space(AK_get_index_addresses(indexName));
AK_block block = (AK_block) AK_read_block(adr_to_read);
root_info root = (root_info) AK_malloc(sizeof (root_info));
...
int address = block->tuple_dict[root->root].address;


Poboljšanje
osim ispravljanja svih pogrešaka smatram da bi bilo potrebno počistiti kod radi bolje preglednosti i lakšeg razumjevanja, također bi bilo dobro dodati još komentara kako bi se ubuduće moglo brže razumjeti što koji dio koda zapravo radi. Neke metode su preko 400 linija koda, na dosta mjesta je i kod koji se ponavlja te nekoliko metoda ima gomilu petlji i if uvjeta jednih unutar drugih što bi trebalo detaljnije proučiti i vidjeti dali je moguće taj problem rješiti drugačije.

**Comment by mschatten** [comment]
AK_btree_create funkcija - potrebno je navedenu funkciju refaktorirati, razdvojiti ju na manje cjeline

AK_btree_delete - fali komentar (opis) funkcije; funkciju je potrebno maknuti da se kod ne ponavlja

AK_btree_search_delete funkcija - potrebno refaktorirati, ne može brisati ili pretraživati (posebno funkcija za brisanje i posebno za pretraživanje); dodati komentare u kod radi lakšeg razumijevanja

AK_btree_insert - fali komentar (opis) funkcije; potrebno je refaktorirati funkciju i razdvojiti navedenu funkciju na manje cjeline

Ak_btree_test - fali komentar (opis) funkcije

**Comment by mschatten** [comment]
Npr. funkcija AK_btree_insert ima cca. 400 linija koda što je ipak malo previše. Trebalo bi se podijeliti u više manjih funkcija. Ima puno ugnježđenih if-else-ova i if-else-ova kombiniranih s različitim petljama što bi se isto moglo efikasnije napraviti. Zbog svih tih ugnježđivanja, automatski je smanjena i čitljivost koda, a i povećana je složenost koda. Postoje pogreške kod testiranja. Neke funkcije nemaju okviran opis što rade i koje parametre primaju.

**Comment by mschatten** [comment]
AK_btree_create
 Kreiranje btree indeksa na prosljeđenom atributu
 Prijedlozi poboljšanja
 Nerazumljiv kod -> više komentara
 Obavljanje više zadataka -> rastavljanje funkcije tako da svaka funkcija ima jedan
zadata
 Ponavljanje blokova koda -> stvaranje novih funkcija s implementiranim blokovima
i pozivanje njih
 Potrebno podijeliti funkciju na više dijelova

AK_btree_delete
 Uklanjanje btree indeksa
 Prijedlozi poboljšanja
 Uopće nema opis funkcije -> staviti komentar s opisom funkcije (spomenuto)

AK_btree_search_delete
 Uklanjanje vrijednosti iz btree indeksa
 Prijedlozi poboljšanja
 Ponavljanje blokova koda -> stvaranje novih funkcija s implementiranim blokovima
i pozivanje njih
 Nerazumljiv kod -> više komentara
 Podijeliti funkciju na više dijelova (spomenuto)

AK_btree_insert
 Unošenje nove vrijednosti u indeks
 Prijedlozi poboljšanja
 Uopće nema opis funkcije -> staviti komentar s opisom funkcije (spomenuto)
 Ponavljanje blokova koda -> stvaranje novih funkcija s implementiranim blokovima
i pozivanje njih
 Nerazumljiv kod -> više komentara
 400 LINIJA KODA -> podijeliti funkciju na više dijelova (spomenuto)

AK_btree_test - test
 Pri pokretanju se ruši program -> PROBLEM
 Prijedlog poboljšanja
 Uopće nema opis funkcije -> staviti komentar s opisom funkcije (spomenuto)
 Potrebno je ispraviti grešku -> vidjeti u kojoj od funkcija je problem i ispraviti ga
(spomenuto)

**Comment by denis910** [comment]
javljam se za rješavanje problema

**Comment by djockovic** [comment]
javljam se za rješavanje problema
