### ISSUE TITLE
akdb/src/rel/selection.c - testovi

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#50]
9) akdb/src/rel/selection.c
- Restrukturirati testove (postoje dva testa i treća funkcija   ..._test_redolog() koja poziva te testove – beskorisno. Treba napraviti jedan dobar test koji će vratiti success ili fail na kraju (trenutno se testovi izvršavaju, ali bez povratne informacije; osim toga, dosta redova se prikazuje poduplano – provjeriti jeli greška u samom testu ili pak glavnoj funkciji?).
- Izbaciti zakomentirani kod (ako je višak)

akdb/src/rel/sequence.c
- Kod funkcije AK_sequence_modify(...) dohvaćanje seq_id-ja napraviti pomoću odgovarajuće već implementirane funkcije za to (AK_sequence_get_id(char *name)), umjesto trenutnog koda na linijama 285-291 (algoritam za dohvaćanje je gotovo isti)

**Comment by Acerinth** [comment]
Ovo ću ja :smiley:

**Comment by mschatten** [comment]
Pridodati komentar vezan uz gore navedeni problem (što još nije u redu - issue #92 ) i pokušati rješiti problem.
