### ISSUE TITLE
Ispraviti product.c i projection.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#51]
10) --product.c--
Dio koda zadužen za iteraciju kroz redove tablica je nepregledan i mogao
bi se izdvojiti u zasebnu funkciju.

--projection.c--
Kod sadrži funkciju  "AK_temp_create_table" koja bi se trebala nalaziti u
nekoj vanjskoj biblioteci.

**Comment by hkisicek** [comment]
I will resolve this issue. Helena Kišiček
