### ISSUE TITLE
Popraviti swig

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#52]
11) swig - testovi ne prolaze i javljaju pogrešku:

python test.py
python -m doctest -v test.py

Ispraviti testove. Integrirati testove u MakeFile (napraviti entry make test koji će pokrenuti doctest gore)

**Comment by idjuras** [comment]
Mogu probati.

**Comment by mschatten** [comment]
Testovi vezani uz update, delete i intersect uvijek padaju, selekcija radi samo na integerima

Problemi s funkcijama za dohvaćanje retka i preimenovanje tablice - test za preimenovanje tablice nije niti implementiran, a za dohvaćanje retka ne radi ispravno

Nepreglednost pokretanja testova - bolja solucija ih razdvojiti u više datoteka kako kod pokretanja testova ne bismo pregledavali milijun redaka

Testovi su nestabilni i prilikom pokretanja vise puta različit broj testova prođe, odnosno padne.
