### ISSUE TITLE
Popraviti archive_log

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#54]
13)  archive_log , recovery i redo_log.

-archive log koristi statičko ime datoteke za kreiranje log-a, to se možda pokušalo popraviti funkcijom AK_get_timestamp, ali ona se zapravo nigdje ne koristi. Ugraditi funkciju u kreiranje log-a. Također, u config.ini ugraditi konfiguracijske elemente koji će odrediti u koji će se direktorij pospremati archive_log, te od tamo učitati direktorij.

**Comment by jurkrizan** [comment]
Ja bih ovaj problem rijesio.
