### ISSUE TITLE
Popraviti memoman AK_flush_cache

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#57]
16) mm -     int AK_flush_cache()
Funkcija ne zapisuje status bloka da je BLOCK_CLEAN nakon što se blok sa
statusom BLOCK_DIRTY zapiše na disk

    table_addresses *AK_get_segment_addresses(char * segmentName)
    table_addresses *AK_get_index_segment_addresses(char * segmentName)
Funkcije sadrže djelove identičnog koda koji se mogu izdvojiti u zasebnu
metodu

    AK_mem_block *AK_get_block(int num)
Funkcija je prevelika i treba je razdvojiti na manje metode
Funkcija ne zapisuje status bloka da je BLOCK_CLEAN nakon što se blok sa
statusom BLOCK_DIRTY zapiše na disk

**Comment by TopHatCroat** [comment]
Javljam se za rješavanje
