### ISSUE TITLE
Memoman testovi

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#58]
17)    void AK_memoman_test()
Test ne daje povratnu informaciju, već samo ispisuje sadržaj učitane memorije

    void AK_memoman_test2()
Test ne daje povratnu informaciju, već samo ispisuje sadržaj nasumičnog
unosa u cache-u

Potrebno je napisati testove sa više čitanja i izmjena u nizu kako bi
mogli lakše izmjerit efikasnost cache-a.

**Comment by TopHatCroat** [comment]
Javljam se za rješavanje
