### ISSUE TITLE
Popraviti table.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#59]
18) -----table.c-----
1. Metoda
AK_get_table_obj_id(char* table) mislim da postoji određena nelogičnost
prilikom prolaska kroz listu odnosno linija broj 891.
row->next->next->data  [slika_1]. To isto moguće da je riješeno sa metodom
naziva:
                char *get_row_attr_data(int column, struct list_node *node) no nigdje
nije iskorištena te bi trebalo testirati ili na sličan način tome
napraviti istu. [slika_2]

2.Metoda
int AK_get_attr_index(char *tblName, char *attrName)
 -> kao rezultat vraća "-1" što ne bi trebao biti slučaj. Postoji
definirana konstanta[slika_3]

**Comment by iMajna** [comment]
I'll solve this issues.
