### ISSUE TITLE
dm - Funkcija AK_allocationtable_dump

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#61]
20)  dm - Funkcija AK_allocationtable_dump (dbman.c: 309) izgleda da ništa ne radi
i zapravo je nedovršena kopija funkcije AK_blocktable_dump (dbman.c: 337),
koju bi također trebalo provjeriti da li proizvodi valjan ispis. Obje nisu
pravilno dokumentirane
--> Ako je potrebno (koristi se negdje ili ima važnu ulogu), završiti funkciju, provjeriti je li funkcija blocktable_dump radi, ako ne radi popraviti. Dokumentirati obje funkcije.

**Comment by Halarious** [comment]
Preuzimam odgovornost
