### ISSUE TITLE
dm - AK_malloc i AK_free

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#62]
21)  dm - Prema sljedećim uputama doslijedno koristiti AK_malloc i AK_free:

- Funckija AK_allocate_block_activity_modes (dbman.c: 413), ako se ne
varam ovaj free unutra nije dobro provjeren, ako pokuša free-at NULL (koji
se mislim u ovom slučaju može dogoditi) ili nealociranu memoriju može doći
do crash-anja. (:419). Svakako ni AK_malloc (:423) nije provjeren da li
dobivamo memoriju koja je zatražena (postoji i AK_free pa bi možda bilo
dosljedno korisititi tu funkciju ako se može?).
Također jedna od mogućih unaprijeđenja je srediti AK_malloc i AK_free

- Funkcija AK_thread_safe_block_access_test (dbman.c: 469), također
AK_malloc neprovjeren par puta (kao i AK_free)

Prema sljedećim uputama pokušati pronaći standardno cross-platform rješenje:
- Funkcija fsize (dbman.c: 602) koristi POSIX stat (što može i ne mora
biti problem ovisno da li se pretpostavlja linux okruženje) za vraćanje
veličine datoteke, no odmah nakon toga se koristi i fseek/ftell u slučaju
da stat ne uspije (iako postavljeno na dosta krivi način). Možda je
vrijedno napomenuti da fseek/ftell metoda nije prema C standardu (pitanje
da li je to stavarno ikome bitno)

**Comment by Halarious** [comment]
Preuzimam
