### ISSUE TITLE
Popraviti view.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#67]
26) view.c

    Nedostaje sam prikaz nekog pogleda u kojem bi se vidjeli atributi i redovi nastali zadanim upitom
    Test kod kojeg se pokušava brisati pogled pomoću ID-a ne prolazi (AK_view_remove_by_obj_id)
    AK_get_rel_exp je suvišna funkcija (identična AK_get_view_query funkciji)

**Comment by hranicd** [comment]
javljam se za rješavanje ovog problema
