### ISSUE TITLE
privileges.c - popravci

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#68]
27) privileges.c

    Nedostaje provjera koja provjerava postoji li već korisnik sa proslijeđenim korisničkim imenom kod funkcije AK_add_user_to_group
    Kod prikaza izvođenja testova bi bilo dobro prikazati i ID nad kojim se izvodi test
    U 7. testu (funkcija AK_add_user_to_group) dolazi do kreiranja negativnog obj_id-a jer se korisnik dodaje u nepostojeću grupu
    U 8. testu (funkcija AK_grant_privilege_group) se ID-evi grupa pretvaraju u negativne (ID od group3 se iz 128 pretvara u -128) te se ID od group 11 sprema u bazi pod -126, iako je 130
    9. test (funkcija AK_revoke_privilege_group) ne briše dozvolu grupe
    11. test (funkcija AK_grant_privilege_user) ispisuje pod atribut name (korisnika) null

**Comment by mflajsek** [comment]
My GF #2
