### ISSUE TITLE
privileges.c - popraviti testove

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#70]
29) 14. test (funkcija AK_check_privilege) vraća krive rezultate - ispisuje da korisnik ima pravo nad tablicom, a zapravo nema
U 15., 17. i 18. testu su pogrešno i loše dokumentirani ispisi testova (u postupku izvođenja su navedeni pogrešni ID-evi) te se kod testa koji briše nepostojeće korisnike iz grupa ispisuje poruka da su korisnici izbrisani, iako oni ne postoje
Poraditi na cjelokupnom prijevodu svih testova, programskom kodu testova koji je gotovo nečitljiv i opisima funkcija koje su na nekim mjestima nejasne

**Comment by mflajsek** [comment]
My GF #1
