### ISSUE TITLE
Popraviti unique.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#72]
31) Unique.c – ne prolaze svi testovi, tj loša su testiranja i ne izvršavaju se do kraja!

 

Kod „pukne“ uz sljedeću prigodnu poruku –

Trying to set UNIQUE constraint on combination of attributes mbr[{(|&&|)}]lastname[{(|&&|)}]weight of table student ...

 

************* Real SIGSEGV occured *************

This means a memory address which is not under

our control has been accessed somewhere in your

code. Please use AK_calloc, AK_free, etc.

You've got some bugfixing to do 😞

Probable current function: AK_tuple_to_string

akdb: auxi/mempro.c:134: AK_debmod_signal_callback: Assertion `mprotect_sigsegv' failed.

Aborted (core dumped)

--> Popraviti i provjeriti da test na kraju ispisuje poruku o uspješnosti.

**Comment by atrajkov4** [comment]
Aleksandar Trajkov Likes this (Y).

**Comment by Acerinth** [comment]
Zainteresirana.... 😃  Zanima me još samo par info o nekim stvarima, ako može da prokomentiramo na labosima?
