### ISSUE TITLE
Popraviti check_constraint.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#73]
32) Check_constraint.c – testiranja nisu dobra, tj ne prolaze svi testovi koji bi trebali (proći ili pasti, ovisi o realizaciji).

 

Od 6 testova, 3 su prošla su očekivanom ocjenom (success ili failure), dok su 3 imala neplanirani ishod.

    Test dobar,
    Test pad,
    Test pad,
    Test dobar,
    Test pad,
    Test dobar.

--> Popraviti i provjeriti da test na kraju ispisuje poruku o uspješnosti.

**Comment by atrajkov4** [comment]
Aleksandar Trajkov likes this (Y).

**Comment by atrajkov4** [comment]
Aleksandar Trajkov ipak likes this
