### ISSUE TITLE
Popraviti between.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#74]
33) Between.c  - testiranja nisu ni isprobana, došlo je do aborta. Kod puca uz prigodnu poruku :

 

inMemoryTable: department

Table name: department

Attribute name: dep_name

Constraint name: dep_name_between

Low boundary: Department of Economy

High boundary: Department of Organization                                  //Ovo je sve dio tablice koda, do ovdje je dobro

*** stack smashing detected ***: ./akdb terminated

Aborted (core dumped)

 
--> Popraviti i provjeriti da test na kraju ispisuje poruku o uspješnosti.

**Comment by atrajkov4** [comment]
Aleksandar Trajkov Likes this (Y).

**Comment by atrajkov4** [comment]
Should be removed, test radi
