### ISSUE TITLE
Popraviti trigger.c i function.c

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#76]
35) akdb/akdb/src/sql/trigger.c

- nedovršeno testiranje, vraća empty iako je proveo delete/insert

akdb/akdb/src/sql/function.c

- test prolazi ali ne vraća nikakav rezultat o uspješnosti

--> Popraviti i dovršiti

**Comment by LexyFOI** [comment]
Javljam se za rješavanje navedenih problema i nedostataka.
