### ISSUE TITLE
Popraviti main.c i MakeFile

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#77]
36) MakeFile:
 - ne radi make doc
--> Ako make doc vrati pogrešku, složiti tako da se korisniku ispiše koje module mora instalirati da bi radilo (doxygen, latex ...)

main.c:
Kod pokretanja aplikacije nije dobro posložena provjera argumenata npr.
kod unosa naredbe ./akdb bbb  se programski kod ne zaustavlja odmah nego
se izvrše neke naredbe AK_init_db_file, AK_memoman_init, itd.
--> Popraviti i odmah ispisati poruku o pogrešnim argumentima. Implementirati argument --help koji će ispisati sve moguće argumente.

**Comment by fstrahij** [comment]
Javljam se za popravljanje navedenih problema
