### ISSUE TITLE
Tip podatka int (posebice id) - povećati

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#78]
Tip podatka int koji se interpretira iz bloka je veličine char (256 je maksimalna vrijednost). Veličinu tipa treba povećati (npr. na 32 bita). Podaci se interpretiraju u funkciji AK_get_row (table.c). Treba provjeriti da se podaci ne interpretiraju još negdje drugdje te nakon promjene veličine tipa provjeriti u svim mjestima gdje se koristi funkcija koja interpretira, je li radi, odnosno treba li nešto promjeniti kako bi radilo.

**Comment by darzunec1** [comment]
Preuzimam zadatak

**Comment by goranalkovic** [comment]
Prijavljujem se za rješavanje.
