### ISSUE TITLE
Popraviti upravljanje dretvama na poslužitelju (srv/server.py)

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#79]
Ne postoji close(). Nakon zavšetka komunikacije sa klijentom, konekcija mora biti očišćena pomoću
close(). Služi za brisanje dump file-ova kako bi se smanjilo opterećenje servera. Dobra praksa nalaže
da se close() korisiti unutar try:finally blocka, kako bi se osiguralo da je funcija close() uvijek pozvana,
pa čak i u slučaju javljanja greške.

Dakle, ako korisnik eksplicitno pošalje neku naredbu za kraj komunikacije ili nakon isteka nekog timeout-a u kojem klijent ne šalje/prima podatke, konekcija se zatvara (dretva i socket).

**Comment by krivite** [comment]
Javljam se za rjesavanje ovog zadatka.
