### ISSUE TITLE
Dokumentacija

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#81]
Proći cjelovito kroz programski kod (c datoteke, h datoteke, py datoteke, sh datoteke i td.) i provjeriti je li dokumentirana svaka konstanta, struktura podataka, funkcija, naredba (za skripte) u doxygen formatu. Ukoliko nije, napisati odgovarajuću dokumentaciju.

**Comment by hkisicek** [comment]
Javljam se za rješavanje.

**Comment by fstrahij** [comment]
Javljam se za rješavanje navedenog problema
