### ISSUE TITLE
Implementirati log

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#83]
Implementirati log koji prati sve operacije sustava (korisnička strana - promjene nad bazom podataka: insert, update, delete, ...) i zapisuje ih u log (destinacijski folder definiran u config.ini). Log se treba zapisivati postepeno (nakon što se jedna datoteka napuni određenim brojem zapisa - broj definiran u config.ini - arhivirati datoteku - gzip - te nastaviti pisati u sljedeću). Format datoteke je takstualni.

**Comment by darzunec1** [comment]
Preuzimam zadatak
