### ISSUE TITLE
Testovi 1, 2, 3 + Git

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#84]
Git + GitHub (commit, push, add, conflict resolve, pravila ponašanja u distribuiranoj okolini ...)

1. auxi: AK_tarjan                2. auxi: AK_observable            3. auxi: AK_observable_patte

**Comment by krivite** [comment]
AK_tarjan
• algoritam u teoriji grafova za pronaženje jako povezanih
komponenti
• kada prelazimo stablo, svaki put kada pretražujemo granu i
vratimo se, provjerimo jesmo li naišli na rub "gornjeg" čvora na
stablu.
• if (node->lowLink == node->index)
• onda smo dovršili Strongly Connected Component - sastoji se od
trenutnog čvora i svih čvorova na staku.

AK_observable i AK_observable_pattern
• Observable pattern se koristi kada postoje jedna naprama više
veze između objekata; ako jedan objekt promijeni stanje, ovisni
objekti moraju biti automatski obaviješteni i ažurirani.
• Observer – objekt koji obaviještavamo
• Observable – objekt čije je stanje od interesa

Test 1 (AK_Tarjan) i 2 (AK_observable) uredno prolaze, no Test 3 (AK_observable_pattern) prilikom pokretanja ne ispisuje ništa.
