### ISSUE TITLE
Testovi 10, 11, 12 + SWIG

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#86]
10. file: Ak_fileio_test          11. file: AK_op_rename            12. file: Ak_filesort 

SWIG

**Comment by darzunec1** [comment]
**1. Test 10 file: Ak_fileio_test**
Kod pokretanja testa kreira se tablica "testna". Podaci se dodaju preko ove linije koda: int AK_add_to_redolog (int command, struct list_node ∗ row_root). Dodano je devet zapisa u tablici. Nakon toga se prema dva zajednička atributa zapisi u tablici ažuriraju.
- MODUL:  file
- GREŠKE: nema
- POBOLJŠANJE: - strukturiranje koda (nejasno i nepregledno definirane varijable, drugim načinom pisanja kod se može smanjiti)

Ak_Insert_New_Element_For_Update - funkcija za unos novog elementa nakon nekog elementa
Ak_insert_row_to_block - funkcija za unos novog elementa u blok
Ak_insert_row - funkcija unosi jedan red u tablicu
Ak_update_row_from_block - ažuriranje podataka u elementu bloka
Ak_delete_row_from_block - brisanje redka iz bloka
Ak_delete_update_segment - funkcija ažurira ili briše cijeli segment tablice
Ak_delete_row - brisanje redka 
Ak_delete_row_by_id - brisanje redka prema ID-u
Ak_update_row - ažuriranje redka
Ak_fileio_test - funkcija za pokretanje testa

**2. Test 11 file: AK_op_rename**
Test preimenovanja operatora. 
- MODUL:  file
- GREŠKE: DA
- POBOLJŠANJE: fix bug-a

************* Real SIGSEGV occured *************
This means a memory address which is not under
our control has been accessed somewhere in your
code. Please use AK_calloc, AK_free, etc.
You've got some bugfixing to do :(
Probable current function: AK_delete_segment
akdb: auxi/mempro.c:134: AK_debmod_signal_callback: Assertion `mprotect_sigsegv' failed.
Aborted (core dumped)


**3. Test 12 file: Ak_filesort**
Ovaj test provjerava funkcionalnost sortiranja unutar tablica. Na početku se ispisuje tablica studenta koja se kasnije sortira od A-Z prema prezimenu studenta. Funkcija koja se koristi za sortiranje je: SORT_TEMP_HELP_student. 
- MODUL:  file
- GREŠKE: nema
- POBOLJŠANJE: n/a

Ak_get_total_headers - vraća broj redaka hedera u bloku
Ak_get_num_of_tuples  - braća broj tuplesa
AK_sort_segment - sortira segment, prima ime tablice i atribut sortiranja
Ak_reset_block - resitira blok kako bi se prikazali sortirani podaci
AK_block_sort - radi sortiranje bloka
Ak_filesort_test  - funkcija za testiranje, sortiranje unutar datoteke


**4. SWIG**
SWIG (Simplified Wrapper and Inferface) je alat za razvoj softvera koji povezuje C i C++ s raznim programskim jezicima više razine. Uključuje skiptne jezike kao što su Javascript, Perl, PHP, Python, Tcl i Ruby. Popis obuhvaća i jezike poput C#, Common Lisp (CLISP, Allegro CL, CFFI, UFFI), D, Idi, Java, uključujući Android, Lua, Modula-3, OCAML, Octave, Scilab... Najčešće se upotrebljava za stvaranje interpretera ili kompajlera, kreiranje korisničkih sučelja, služi kao alat za testiranje i prototipiranje C/C++ softvera. 
Besplatan je i kod koji SWIG generira kompatibilan je s komercijalnim i nekomercijalnim projektima.

**5. Poboljšanje generalno**
- ispravak oko alokacije memorije, primjer u AK_op_rename testu
- modifikacija funkcija koja se proteže kroz cijeli kod -> Ak_Insert_New_Element_For_Update
 
**6. Prezentacija**
Prezentacija se nalazi na ovom linku: tinyurl.com/zunec-fobp
