### ISSUE TITLE
Testovi 7, 8, 9 + MakeFile 

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#87]
Makefile  

7. file: Ak_id                    8. file: AK_lo                    9. file: Ak_files_test

**Comment by mateaB** [comment]
## MakeFile

Makefile je datoteka koja sadrži skup smjernica korištenih u alatu za automatizaciju izrade. Ona usmjerava kako sastaviti(compile) i povezati(link) program. 
Korištenje Makefile-a može znatno smanjiti vremena izgradnje ako se promijenilo samo nekoliko izvornih datoteka.
Kada se izvorna datoteka promijeni, ona mora biti recompilana. Ako se datoteka zaglavlja promijenila, svaka izvorna datoteka koja sadrži datoteku zaglavlja mora biti recompilana kako bi bila sigurna. Svaka kompilacija stvara objektnu datoteku koja odgovara izvornoj datoteci. Konačno, ako je bilo koja izvorna datoteka recompilana, sve datoteke objekta, bilo nedavno napravljene ili spremljene iz prethodnih kompilacija, moraju biti povezane zajedno kako bi se stvorio novi izvršni program. Upute o njihovim ovisnostima navedene su u makefileu. Ako nijedna datoteka koja je preduvjet nije promijenjena od posljednjeg zakljucavanja programa, ne poduzimaju se akcije. 

## AK_id

Ona se nalazi na lokaciji: src/file/id.c

Sastoji se od tri metode:

- AK_get_id() koja vraća int.

- AL_get_table_id(char *tableName) koja vraća char.

- AK_id_test() koja ne vraća nista, odnosno ona je void

## AK_lo

"lo" znači: large object-s

Nalazi se na lokaciji: src/file/blobs.c

Sastoji se od metoda:

- Ak_File_Metadata_mailloc() koja vraća AK_File_Metadata

- *AK_GUID() koja vraća char

- AK_folder_exists(char *foldername) koja vraća int

- AK_mkdir(const char *path) koja vraća int

- AK_copy(const char *from, const char *to) koja vraća int

- AK_concat(char s, char *s2) koja vraća char

- *AK_clear_allnewlineIchar *s) koja vraća char

- AK:check_folder_blobs() koja vraća int

- AK_split_path_file(char **p, char **f, char *pf) koji nista ne vraća, tj void je

- AK_write_metadata(char *oid, AK_File_metadata meta) koja vraća int

- AK_reread_metadata(char *oid) koji vraća AK_File_Metadata

- *AK_lo_import(char *filepath) koja vraća char 

- AK_lo_export(char *oid, char *filepath) koja vraća int

- AK_lo_unlink(char *oid) koji vraća int

- AK_lo_test koja nista ne vraća, odnosno void je


## Ak_files_test

Nalazi se na lokaciji: src/file/files.c

Sastoji se od metoda:

- AK_initialize_new_segment(char *name, int type, AK_header *header) koja vraća int

- AK_initialize_new_index_segment(char *name, char *table_id, int attr_id, AK_Header *header) koja vraća int

- AK_files_test() koja također kao i AK_lo_test ne vraća ništa, odnosno void je
