### ISSUE TITLE
Testovi 13, 14, 15 + GCC

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#88]
13. file: Ak_filesearch           14. file: AK_sequence             15. file: AK_op_table

GCC

**Comment by darmirkov** [comment]
## Ak_filesearch
Modul u kojem se nalazi : file ->filesearch.c

- AK_search_unsorted - Pretraga kroz ne sortirane vrijednosti više atributa u segmentu. Vraćaju se samo n-torke koje imaju jednake atribute. Samo jedan  vrijednost ili raspon se pretražuje. Kod raspon podržava pretragu po: TYPE_INT, TYPE_FLOAT, TYPE_NUMBER, TYPE_DATE, TYPE_DATETIME, TYPE_TIME. 

- AK_deallocate_search_result – Funkcija dealocira memoriju korištenu kao rezultat Ak_search_unsorted

- AK_filesearch_test - Funkcija za testiranje file search-a

Prilikom prvog pokretanja test se uredno izvrši, ali nakon drugog pokušaja testiranja test se raspadne.

## AK_sequence

- Modul u kojem se nalazi: file ->sequence.c

- AK_sequence_add – funkcija za dodavanje sekvence

- AK_sequence_remove – funkcija za uklanjanje sekvence

- AK_sequence_current_value – funkcija vraća trenutnu vrijednost sekvence

- AK_sequnece_next_value – funkcija vraća vrijednost sljedeće sekvence i zapisuje je u sistemsku tablicu kao trenutnu vrijednost

- AK_sequence_get_id – funkcija koja dohvaća trenutni id sekvence

- AK_sequence_rename – funkcija koja preimenuje sekvencu

- AK_sequence_modify – funkcija koja služi za modifikaciju sekvence

- AK_sequence_test – funkcija za testiranje sekvence

Test nije uspješan, raspadne se kod modificiranja sekvence.

## AK_op_table
Modul u kojem se nalazi: file ->table.c

- AK_print_table  - funkcija koja ispisuje tablicu

- AK_table_empty – provjera da li je tablica prazna

- AK_num_attr – određuje broj atributa u tablici

- AK_get_num_records – funkcija koja govori koliko ima redova u tablici

- AK_get_row – funkcija koja dohvaća i ispisuje red u tablici s određenim uvjetom

- AK_get_attr_name – funkcija koja dohvaća ime za zero-based indeks

- AK_get_attr_index – funkcija koja dohvaća zero-based indeks za atribute

- AK_get_tuple – dohvaća n-torku podataka

Test se uredno izvršava.

## GCC - The GNU Compiler Collection

-  Jezici koji se koriste: C, C++, Objective-C, Fortran, Ada, and Go
- GCC je skup programerskih prevoditelja koji je nastao iz GNU projekta.
- To je opensource program i besplatan je. 
- Koristi se u unix sustavima. 
- Razvio ga je 1987. Richard Stallman. 
- Koristi se za razvoj drugih software-a.
