### ISSUE TITLE
Testovi 48, 49, 50 + PyParsing

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#93]
48. sql: Ak_constraint_betwee     49. sql: AK_check_constraint      
50. sql: AK_constraint_names

**Comment by nkuzir** [comment]
## **Test 48: sql: Ak_constraint_between** 

Uočeni nedostaci: Prvo pokretanje testa prolazi u redu, drugi pokušaj izbacuje nas iz programa uz poruku:

*********** Real SIGSEGV occured ***********
This means a memory address which is not under
our control has been accessed somewhere in your
code. Please use AK_calloc, AK_free, etc.
You've got some bugfixing to do 😞
Probable current function: Ak_constraint_between_test
akdb: auxi/mempro.c:134: AK_debmod_signal_callback: Assertion `mprotect_sigsegv' failed.
Aborted (core dumped)

Također, kod je prilično opsežan i može ga se bolje strukturirati radi lakše preglednosti.

## **Test 49: sql: AK_check_constraint**

Prvo pokretanje testa prolazi u redu, drugo pokretanje ne prolazi kako je očekivano, testiranja nisu dobra i ne prolaze svi testovi koji bi trebali - od šest testova, tri su prošla očekivano (success ili failure), 
dok su 3 imala obrnuti ishod. 1. Test prolazi, 2. Test pada, 3. Test pada, 4. Test prolazi, 5. Test pada 6. Test prolazi. 

## **Test 50: sql: AK_constraint_name**

Test svaki puta uredno prolazi, no potrebno je provjeriti jesu li sva ograničenja obuhvaćena provjerom i eventualno dodati ukoliko neko fali.
