### ISSUE TITLE
Testovi 26, 27, 28 + UnitTest

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#94]
26. rel: AK_op_union              27. rel: AK_op_join               28. rel: AK_op_product 
 UnitTest

**Comment by davbijeli** [comment]
**Test 26.**
AK_op_union test uredno prolazi!

**Test 27.** 
AK_op_join test ne prolazi! Ispisuje se poruka da tablica _nat_join_test_ ne postoji.
Konstanta MAX_ATTRIBUTES ograničava broj stupaca koji se mogu pohraniti u jednom memorijskom bloku. Dio atributa koji se ne uspijeva zapisati u jedan blok zapisuje se u drugi.

**Test 28.**
AK_op_product test prolazi!
Napomena za MAX_ATTRIBUTES isto kao i kod testa 27.
