### ISSUE TITLE
Testovi 29, 30, 35 + Doxygen

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#95]
29. rel: Ak_aggregation           30. rel: AK_op_intersect     35. rel: AK_op_difference 

Doxygen

**Comment by nsinjori** [comment]
# **29. rel: Ak_aggregation**

Ovaj test sadrži 7 funkcija.

### int AK_header_size(AK_header *header)
- računa koliko atributa se nalazi u headeru
### void AK_agg_input_init(AK_agg_input *input)
- inicijalizira ulazni objekt za agregaciju s početnim vrijednostima
### int AK_agg_input_add(AK_header header, int agg_task, AK_agg_input *input)
- dodaje header u prethodno inicijalizirani ulazni objekt
### int AK_agg_input_add_to_beginning(AK_header header, int agg_task, AK_agg_input *input)
- dodaje header sa zadatkom na početak ulaznog objekta
### void AK_agg_input_fix(AK_agg_input *input)
- koristi se kod funckije AVG kako bi se najprije izvršila funkcija COUNT, a zatim SUM
### int AK_aggregation(AK_agg_input *input, char *source_table, char *agg_table)
- ulazni parametri:
	ulazni objekt s popisom atributa po kojima se radi agregacija i njeni tipovi
	naziv ulazne tablice
	naziv za tablicu rezultata
- pomoću for petlje prolazi se kroz ulazne zadatke (GROUP, COUNT, SUM, MAX, MIN, AVG)


### void Ak_aggregation_test()
Glavni test koji radi agregaciju nad tablicom student.
Grupiranje po prezimenu, prosjek pete kolone (visina), zbroj prezimena za isto ime, suma težine po imenima, maksimalna težina grupirana po imenu, minimalna težina grupirana po imenu

modu: rel
## greška: Floating point exception (core dumped)

### poboljšanje: zamijeniti pojedine dijelove s AK_drop_table() (ako postoji)




# 30. rel: AK_op_intersect

Ovaj test sadrži funkciju koja radi presjek dviju tablica. Rezultat je tablica u kojoj se nalaze podaci koji se nalaze u obje ulazne tablice.
### int AK_intersect(char *srcTable1, char *srcTable2, char *dstTable)
Parametri koje prima funkcija su naziv prve tablice, naziv druge tablice te naziv tablice rezultata.
Ako je rezultat uspješan vraća se EXIT_SUCCESS, inače EXIT_ERROR.
Inicijalizira se novi segment (tablica) sa potrebnim zaglavljem. Zatim se prolazi kroz unesene tablice i provjerava da li postoje jednaki redovi. Ako se pronađu jednaki upisuju se u tablicu rezultata.

### Ak_op_intersect_test()
Uzima tablicu professor i tablicu assistant te kreira tablicu intersect_test.
Test uredno prolazi.


modu: rel
## greška: nema
### poboljšanje: dealociranje memorije kod korištenja privremenih blokova



# 35. rel: AK_op_difference

Ovaj test sadrži funkciju za razliku dviju tablica.
### int AK_difference(char *srcTable1, char *srcTable2, char *dstTable)
Ulazni parametri su nazivi dviju tablica te naziv izlazne tablice.
Adresa tablica dohvaća se pomoću njihovih naziva. Pomoću adresa alociraju se potrebni blokovi i zatim se provjerava da li je shema tablica jednaka. Ukoliko nije vraća se EXIT_ERROR.
Funkcija uspoređuje svaki blok prve tablice sa blokom iz druge tablice. Ukoliko postoji razlika ona se zapisuje u tablicu rezultata.

### Ak_op_difference_test()
Glavni test koji koristi prethodnu funkciju. Uzimaju se tablice assistant i professor te se unosi naziv destinacijske tablice. Vrši se provjera da li destinacijksa već postoji, ako postoji vraća se EXIT_SUCCESS, a u protivnom se radi razlika unesenih tablica.

modu: rel
## greška: nema
### poboljšanje: dealociranje memorije kod korištenja privremenih blokova


# Doxygen
Koristi se za generiranje dokumentacije. Izvlaći dokumentaciju iz označenih komentara koji se nalaze u kodu. Podržava većinu jezika C, Objective-C, C#, PHP, Java, Python, IDL...

Može generirati HTML dokumentaciju ili pak LATEX oblik.
Postoji mogućnost za RTF (MS-Word), PostScript, hyperlinked PDF, compressed HTML, te Unix stranice pomoći.
Dokumentacija se generira iz koda i samim time olakšava njeno ažuriranje.
Mogućnost izrade grafova zavisnosti, dijagrama nasljeđivanja i sl.
